from .utils import safe_md
from ..models import Conclusion, Alert

def format_description(alert: Alert, conclusion: Conclusion) -> str:
    # Jira Cloud supports a specific document format; to keep this lean we use plain text/Markdown-ish.
    # If you need Atlassian Document Format (ADF), wrap here.
    actions = conclusion.actions or {}
    immediate = actions.get("immediate", [])
    short_term = actions.get("short_term", [])
    long_term = actions.get("long_term", [])

    md = f"""    ## 🔔 Incident Summary
{safe_md(conclusion.summary)}

## 🧠 Root Cause
{safe_md(conclusion.root_cause)}

## ❓ Why It Happened
{''.join([f'- {safe_md(x)}\n' for x in (conclusion.why_it_happened or [])]) or '- (no data)\n'}

## 🛠 Recommended Actions

### Immediate
{''.join([f'- {safe_md(x)}\n' for x in immediate]) or '- (none)\n'}

### Short Term
{''.join([f'- {safe_md(x)}\n' for x in short_term]) or '- (none)\n'}

### Long Term
{''.join([f'- {safe_md(x)}\n' for x in long_term]) or '- (none)\n'}

## 📌 Alert
- ID: {safe_md(alert.id)}
- Service: {safe_md(alert.service)}
- Type: {safe_md(alert.type)}
- Severity: {safe_md(alert.severity)}
- Timestamp: {safe_md(alert.timestamp)}

## 📊 Confidence
{safe_md(conclusion.confidence)}

## 🤖 Generated by
AI Operations Agent (review required)
"""
    return md
